version: '3.8'

services:
  ttyd:
    build:
      context: .
      dockerfile: Dockerfile.ttyd
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ttyd.rule=Host(`localhost`)"
      - "traefik.http.services.ttyd.loadbalancer.server.port=3000"
    volumes:
      - ./labs:/labs
      - ./storage/lab_data:/home/kali/lab_data
      - ttyd-sessions:/tmp/sessions
    environment:
      - RAILS_HOST=web
      - RAILS_PORT=3001
      - TTYD_PORT=3000
      - TERM=xterm-256color
    healthcheck:
      test: ["CMD", "/usr/local/bin/ttyd-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - default
      - lab-network
    cap_add:
      - NET_ADMIN  # Para permitir configuración de red
    security_opt:
      - apparmor:unconfined  # Permitir operaciones que requieren escalado de privilegios

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - ./storage:/app/storage
    depends_on:
      - ttyd
    environment:
      - RAILS_ENV=development
      - TTYD_HOST=ttyd
      - TTYD_PORT=3000
      - PORT=3001
    networks:
      - default
      - lab-network
    cap_add:
      - NET_ADMIN  # Para permitir configuración de red
    security_opt:
      - apparmor:unconfined  # Permitir operaciones que requieren escalado de privilegios

  lab-network:
    image: alpine:latest
    command: sh -c "tail -f /dev/null"
    networks:
      - lab-network
    cap_add:
      - NET_ADMIN
      
  # Servicio para escenarios de defensa/ataque
  target-host:
    build:
      context: .
      dockerfile: Dockerfile.ttyd
    networks:
      - default
      - lab-network
    volumes:
      - ./labs:/labs
    environment:
      - SCENARIO_TYPE=target
      - RAILS_HOST=web
      - RAILS_PORT=3001
      - TTYD_PORT=3000
      - TARGET_USER=target  # Usuario específico para la máquina objetivo
    cap_add:
      - NET_ADMIN
    # Puerto diferente para evitar conflictos con el ttyd principal
    ports:
      - "3030:3000"

networks:
  default:
    driver: bridge
  lab-network:
    driver: bridge
    internal: true  # Red aislada para laboratorios
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  ttyd-sessions:  # Volumen persistente para sesiones tmux