name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: ciberseguridad_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    env:
      RAILS_ENV: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ciberseguridad_test
      SCHEMA: "false"  # Ignorar extensiones de Supabase
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: Configurar base de datos
      run: bundle exec rake supabase:db_create
        
    - name: Migrar esquema 
      run: bundle exec rake supabase:migrate
        
    - name: Run tests
      run: bundle exec rake supabase:test
      
    - name: Run rubocop
      run: bundle exec rubocop --parallel
